### ISSUE TITLE
Unicode Support?

### ISSUE THREAD

**Issue by cipherboy** [lotuskip/cursetag#4]
I notice that when I tag a recording (`.flac`) with Unicode characters (e.g., August Nörmiger), it shows up as `NÃ¶rmiger` in all of my players and in cursetag after writing, closing cursetag, and reopening the file. 

If I had time, I'd take a look and submit a PR, but not sure when I'd get time to do so. Any thoughts for getting started?

(Alternatively, any other curses-based tagging software suggestions would be appreciated).

Thanks,

Alex

**Comment by lotuskip** [comment]
Indeed, there are issues with UTF-8, and they reside in all likelihood within encodings.cpp which ought to be rewritten completely. It's not very big but, well, I just took a glance, and one comment, for instance, says "NOTE: assuming int is 32-bit..!" -- wtf??

Really, I wrote this stuff a long time ago and mostly for myself. The mentioned rewriting could certainly use existing UTF-8 handling routines, of which I was either unaware or suspicious back in the day. I myself am very unlikely to to work on it, partly due to lack of time&motivation, partly due to a rapidly developed reluctance to use C++.

For anyone who finds cursetag useful or possessing potential, I highly recommend forking, or even better, starting from scratch and maybe taking some ideas/snippets from my code. Observe that there is no licence / the code is Public Domain / whatever expression you prefer.

**Comment by xaizek** [comment]
> Observe that there is no licence / the code is Public Domain / whatever expression you prefer.

Actually, you should add one (CC0 is a good way of putting things into public domain if that's what you want), otherwise formally people can't use the code. Not having a licence is not equivalent to public domain, in general it's equivalent to forbidding every use.

**Comment by lotuskip** [comment]
The README mentions what I feel about "licencing". Maybe it doesn't fly according to the predominant Roman-derived jurisprudence, but then I'd rather not conform. I know I'm difficult that way. Sorry.

Formally or not, anyone, feel free to do whatever! Do be civil about it, though.

**Comment by xaizek** [comment]
I don't think Romans have much to do with ugly copyright laws, which seem to have originated in England. I'm just saying that absence of a license might prevent use of code, say Linux distributions probably won't consider any project without a license.

[CC0](https://creativecommons.org/publicdomain/zero/1.0/) is a legal equivalent of saying "I don't care either way." so that even lawyers can understand it :) If you eventually choose to apply it, just saying "Copyright and related rights are waived via CC0" should be enough.

**Comment by m040601** [comment]
> Owner lotuskip commented on Jan 31, 2018
> 
> ... Indeed, there are issues with UTF-8,...
> ... ought to be rewritten completely. ...
> 
> ... I wrote this stuff a long time ago and mostly for myself.
> ...  I myself am very unlikely to to work on it
> ...  due to lack of time&motivation, 
> 
> ... I highly recommend forking


Hi lotuskip,

first of all thank you for creating this nice little tool.  Until today I only knew about "kid-common" and "tageditor-cli" for the console. I'm a command line fanatic and  heard about "cursetag"  today, because a PKGBUILD for Archlinux was just created today, https://aur.archlinux.org/packages/cursetag-git.

But, coming back here to github to check it out, I noticed this issue, and that this repo has the last commits from 2020.


So I was just wandering if you could add one line or two here, or to the README.

- Were those issues with UTF8 resolved ?
- Are you, yourself, still using cursetag ?
- Any planned future development ?

Thanks in advance

**Comment by lotuskip** [comment]
Unfortunately, the answers are no, no, and no. I haven't given this piece of abandonware any thought the past years. I suppose it would still be my go-to tool if I ever needed to modify audio tags in bulk, but haven't had that need. Thank you for your interest and kind comments, nevertheless.

**Comment by xaizek** [comment]
Sent PR to fix this. I had a filling it was something trivial.
